### ISSUE TITLE
Sacrifice unittest capabilities or not test on PHP <= 7.0

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#109]
As we are using doctrine and other packages, which need PHP 7.1, we cannot do a `composer install` on any version below 7.0.

This means that we can only run linting for PHP 7.0 and lower.

Do we need to be able to run unittests or coding standards checks on other PHP versions?

**Comment by kraftner** [comment]
Is that actually true? Running `composer depends php` doesn't show anything with a requirement above `5.6.*`

What might be true is that when running `composer install` in `PHP 7.1`. this might install versions that don't work in earlier PHP versions. But in that case removing the lock file and reinstalling should fix this.

To answer the actual question, personally I don't care about running those things in `<7` but if it doesn't cause extra effort, why not...

**Comment by moorscode** [comment]
I think I got confused because I was running PHP 7.* locally when running composer install. Thus installing the newer versions of the dependencies.

As long as we lint for PHP 5.2 and PHP 7.*, we should be certain that the code is compatible with these versions.
