### ISSUE TITLE
SEO Readability Score Eye not scanning ACF WYSIWYG Fields

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoast-acf-analysis#12]
### What did you expect to happen?

I expected the plugin to be able to scan the ACF WYSIWYG fields for readability and create an "eye" if something is wrong.
### What happened instead?

It did not. 
### How can we reproduce this behavior?

**1.Create ACF field with WYSIWYG editor**

![screen shot 2016-09-06 at 11 06 19 am](https://cloud.githubusercontent.com/assets/8238074/18278959/f61e6314-7421-11e6-87ad-fa5a0421ab6e.png)

**2.Add field to Titles and Metas Section**

![screen shot 2016-09-06 at 11 12 17 am](https://cloud.githubusercontent.com/assets/8238074/18279264/e0f50cbc-7422-11e6-840a-82eff4adeece.png)

**3. Add content to the ACF field and see that it does not scan**

![1](https://cloud.githubusercontent.com/assets/8238074/18279023/220144d8-7422-11e6-8bba-3629dc03c1b3.jpg)

**4.Remove content from ACF field and add content into main WYSIWYG editor. See that it works.**

![screen shot 2016-09-06 at 11 03 36 am](https://cloud.githubusercontent.com/assets/8238074/18279063/47a17780-7422-11e6-844c-841b360be7a8.png)

![screen shot 2016-09-06 at 11 03 48 am](https://cloud.githubusercontent.com/assets/8238074/18279047/39c69e60-7422-11e6-8252-5d0591113a93.png)

Can you provide a link to a page which shows this issue? n/a
### Technical info
- WordPress version: 4.6
- Yoast SEO version: 2.4.2
- ACF : 4.4.8
- Yoast SEO: ACF Analysis: 1.2.0

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 145909 when this conversation has been closed.

**Comment by kraftner** [comment]
This is not yet implemented. See #2 for more information.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 160063 when this conversation has been closed.

**Comment by kraftner** [comment]
This is now included in 2.0 which was released today! :tada:
