### ISSUE TITLE
Repeater Field Issue

### ISSUE THREAD

**Issue by Mo-1989** [Yoast/yoast-acf-analysis#123]
I'm having a bit of trouble understanding why my ACF Repeater Field is not being analyzed by Yoast SEO and ACF Content Analysis for Yoast SEO.

I'm using all the latest versions of each plugins and I've been using the ACF Repeater add-on for a while. Recently I've noticed that the repeater fields won't get included in the SEO analysis. But the fields that aren't repeater, they get included. Which is problematic because most pages have Repeater fields with their text and images not getting included into the page analysis. 

I'm not exactly sure when it stopped analyzing the ACF Repeater field. Maybe an update caused this since it was fine previously. I haven't been able to find a solution for this yet. If someone can provided some information or help, thank you.

**Comment by kraftner** [comment]
Can you please add some more information about your setup, at least the following information?

> ### Technical info
> * WordPress version: 
> * ACF Content Analysis for Yoast SEO version: 
> * Yoast SEO version: 
> * ACF type: 
> * ACF version: 
> * Relevant plugins in case of a bug:

**Comment by kraftner** [comment]
Thanks for the added details. I can now see why this isn't working for you: As stated in the [plugin description](https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/) the addons for ACF 4 aren't supported. So you'll need to update to ACF 5 to be able to use any Pro Features like Repeaters. Especially now with the [imminent release of ACF 5 Free](https://www.advancedcustomfields.com/blog/acf-5-early-access/) we'll not be putting further effort into extending support for ACF 4, sorry. Hence I am closing this as wontfix, but I have created #124 to at least warn people like you about this.

**Comment by Moe-1989** [comment]
Thanks for your help @kraftner To update to ACF 5, do I have to to get ACF PRO (https://www.advancedcustomfields.com/pro/)? Or do this to my free ACF with the version 4.4.12: https://www.advancedcustomfields.com/resources/upgrade-guide-version-5/?

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/yoast-acf-analysis/issues/191
