### ISSUE TITLE
[Plugin Request] Create a plugin to be compatible with the Custom Field Template plugin

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoast-acf-analysis#16]
Currently, the plugin only works with Advanced Custom Fields. We should consider creating a plugin to work with the [Custom Field Template plugin](https://wordpress.org/plugins/custom-field-template/).

**Comment by kraftner** [comment]
I'm not really sure making this inside *this* plugin is a great idea. 99% of the stuff this plugin does is ACF specific as it depends on the markup and client side JS specific to ACF.
So if you need support for another Custom Field Plugin I'd say create a new plugin so this plugin can stay focused.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 156230 when this conversation has been closed.

**Comment by kraftner** [comment]
Probably in a new repo of a non-existing glue plugin for Custom Field Template. :wink: 
I dare closing this now as I think it is way out of scope of this plugin.
