### ISSUE TITLE
What is the expected result upon Activation??

### ISSUE THREAD

**Issue by nexjsystems** [Yoast/yoast-acf-analysis#167]
I just have a question. 

I have AFC 5, Yoast Premium and your latest version of Yoast AFC Analysis (latest version of WP). 

After installing Yoast AFC and navigating to a page with multiple custom fields, I do not see any extra Yoast Analysis boxes below the custom fields.. Am I supposed to see multiple Yoast Analysis boxes OR are all custom fields tied to the main Yoast Analysis Box? 

I just don't know what the expected results are.

**Comment by moorscode** [comment]
Hi @nexjsystems 

Sorry for the late reply.

The ACF Analysis plugin ties the ACF fields to the main Yoast SEO box silently.
All content provided will be integrated into the SEO and readability analyses.

I hope this answers your question.
