### ISSUE TITLE
Image inside a repeater fields not analysed

### ISSUE THREAD

**Issue by cedriccharles4** [Yoast/yoast-acf-analysis#17]
Hello,

Thank you for your plugin. Here I have a classic page with multiple fields groups. In one of my field group, I have a repeater that contains an image field. My image is set but YOAST told me that no image were found...

Why is that ?

Thank you in advance !

**Comment by stirtingale** [comment]
Just wanted to add to this - same issue applies for layouts built within the Flexible Content Repeater. 

It would be ace to run the check within any/all arrays that ACF uses

**Comment by kraftner** [comment]
We're currently working on a new version that will also include this feature.

**Comment by stirtingale** [comment]
@kraftner awesome!! Would that also include recognising if an alt attribute is set on that image/appears on the front-end? That is the only other problem using images in any ACF fields?

**Comment by kraftner** [comment]
Yes that should work as well. At least if the `alt` that appears on the front-end is what is set on the image attachment. If you mess with it in your template it won't work.

If you want to get your hands dirty and give it a try you can have a look at the [`features/acf-5`](https://github.com/Yoast/yoast-acf-analysis/tree/features/acf-5) branch. While it should be pretty stable be warned - it is still work in progress. :construction:

**Comment by kraftner** [comment]
This is now included in 2.0 which was released today! :tada:

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/yoast-acf-analysis/issues/191
