### ISSUE TITLE
WYSIWYG Field content integration

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#2]
Because of the use of tinyMCE the content of WYSIWYG fields are not yet appended to the content analysis.

ACF has document triggers for acf/wysiwyg/(blur/focus/loaded) so integration should not be impossible.

**Comment by kraftner** [comment]
So I looked into this for my own integration. It seems that at least on `blur` a `change` event is triggered on the textarea corresponding to the WYSIWYG field.

So if you listened to `change` [here](https://github.com/Yoast/yoast-acf-analysis/blob/849ec5f70de4ac530e487af460d5fbd32ec2728a/js/yoast-acf-analysis.js#L21) it should work. Only downside is that one has to leave the textarea for a recalculation to happen.

**Comment by kraftner** [comment]
In the meantime I realized that ACF Pro (Version 5) differs quite a lot in the way the JS works from the free ACF (version 4). So my findings might only be valid for the Pro Version.

**Comment by kraftner** [comment]
This would be handled by #4

**Comment by silicondales** [comment]
Hi,

Looking to hook a way to calculate contents of a custom WYSIWYG editor which stores values in custom fields, and use this for calculating Yoast scores where word count = 0 (but shouldn't).

Did you make any headway with this?

**Comment by kraftner** [comment]
This is now included in 2.0 which was released today! :tada:

**Comment by silicondales** [comment]
Wow this was from a while ago! Well done. Client in question is no longer around to test.
