### ISSUE TITLE
Show notice when the plugin is activated to recalculate SEO scores

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#22]
Original issue: https://github.com/Yoast/wordpress-seo/issues/7463

When this plugin is activated (next to Yoast SEO and ACF) we should throw a notification telling the user to recalculate their post/pages.

This notification should be dismissible and show be removed after the recalculation is complete.
This will require some work in Yoast SEO (adding a `do_action` after recalculation is complete).

**Comment by monbauza** [comment]
Please inform the customer of conversation # 207462 when this conversation has been closed.

**Comment by kraftner** [comment]
Not sure how this could be done technically. Either you re-introduce a server side way of handling this (that once existed here but was removed. See https://github.com/Yoast/yoast-acf-analysis/commit/ffdf9db8910ab7faea0e72ebc7b406cd5361fd3c for details).
Or one would need to manually open and re-save all affected posts. Am I missing something here?

**Comment by kraftner** [comment]
I am tempted to close this as `wontfix` because I do not currently see a way to do this with the way Yoast SEO is client side JS only nowadays.

**Comment by omarreiss** [comment]
I agree with @kraftner. Recalculation is too small a benefit for the amount of work and expected pain it will cause (as became clear the last time we tried it). The content analysis is still super useful without it. Only the SEO columns and dashboard widget suffer from this. We might reconsider when we are going to implement more site wide SEO features. Until that time, closing as `wontfix`.
