### ISSUE TITLE
Content of ACF blocks with mode "auto" is not analyzed

### ISSUE THREAD

**Issue by freinbichler** [Yoast/yoast-acf-analysis#261]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
ACF Gutenberg blocks which are initialized with mode "auto" (fields render INSIDE the Gutenberg block on click) are not recognized by Yoast. Without mode "auto", where the fields are rendered in the sidebar, everything works as expected.

See my comment https://github.com/Yoast/yoast-acf-analysis/issues/241#issuecomment-641321308 in issue https://github.com/Yoast/yoast-acf-analysis/issues/241

To reproduce, register your blocks with the following option:
```
acf_register_block_type(array(
  ...
  'mode' => 'auto',
  ...
));
```

### Technical info
* WordPress version: 5.4.2
* ACF Content Analysis for Yoast SEO version: 2.4.1
* Yoast SEO version: 14.3
* ACF type: Pro
* ACF version: 5.8.12

**Comment by alexvandervegt** [comment]
I have the same issue
