### ISSUE TITLE
Warning: ACF Content Analysis for Yoast SEO requires Yoast SEO for WordPress 14.6 or higher, please update the plugin.

### ISSUE THREAD

**Issue by Fashionhero** [Yoast/yoast-acf-analysis#274]
* [ x] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

My site is reporting this error:

ACF Content Analysis for Yoast SEO requires Yoast SEO for WordPress 14.6 or higher, please update the plugin.

I am not running Yoast, I am running Yoast Premium 12.3. What to do?

Cheers

### How can we reproduce this behavior?
1. 
2. 
3. 

### Technical info
* WordPress version: 
* ACF Content Analysis for Yoast SEO version: 
* Yoast SEO version: 
* ACF type: 
* ACF version: 
* Relevant plugins in case of a bug:

**Comment by moorscode** [comment]
Hello @Fashionhero 

Yoast Premium is basically Yoast SEO with added features. You should update Yoast Premium to the latest version to make this warning go away, and the plugin work.

Updating to the latest version is always our recommendation, as we constantly improve the plugin with features, bugfixes and performance enhancements.
