### ISSUE TITLE
We need to have a message for moving to the recommended plugin

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#28]
As we are going to deprecate this plugin and move the functionality to the Angry Creative: ACF Content Analysis for Yoast SEO plugin, we need to inform the user about this change and guide them to use the other plugin.

## Functionally

**In any case**
  - Describe why and what is going to happen

**The user is able to activate/deactivate plugins**
  - Provide search for Angry Creative plugin
  - If both plugins are active, show a notification to disable and remove this plugin
  - The functionality of this plugin can be disabled for this user, to force them to switch plugins

**The user is -not- able to activate/deactivate plugins**
  - Show the message that a better plugin is available, suggest to contact the person who maintains the website to switch to the new plugin
  - The functionality of this plugin must not be disabled because it takes away a feature they cannot control
  - Refrain from showing any other dependency notifications

**Comment by kraftner** [comment]
fixed by #29
