### ISSUE TITLE
Is this plugin compatible with free ACF Version 5.9.4?

### ISSUE THREAD

**Issue by wpfan1000** [Yoast/yoast-acf-analysis#287]
* [ x] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

I went to:
https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/

Which says:
This Plugin is compatible with the free ACF 4 Version

Yet the current free ACF version is 5.9.4

So either:

Your plugin is not compatible with free ACF version 5.9.4
or
You have not updated the plugin's description at https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/

Please let me know what's up.

bedankt

### How can we reproduce this behavior?
1. 
2. 
3. 

### Technical info
* WordPress version: 
* ACF Content Analysis for Yoast SEO version: 
* Yoast SEO version: 
* ACF type: 
* ACF version: 
* Relevant plugins in case of a bug:

**Comment by jeroenrotty** [comment]
Hey @wpfan1000,
I'm letting you know that version 3.1 we recently released has a minimum of ACF 6.0 - as seen on https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/#developers
