### ISSUE TITLE
Consider custom ACF fields in analysis?

### ISSUE THREAD

**Issue by aronvandervalk** [Yoast/yoast-acf-analysis#347]
### Please give us a description of what happened.
Hi, We run a couple of websites that have custom ACF fields. We use the https://github.com/Hube2/acf-medium-editor Medium editor plugin to enable a simple and extendable Medium Editor Field for adding a bold, italic or color options (for instance) to specific field sets.

### Please describe what you expected to happen and why.
It appears that these fields are not considered by the Yoast ACF analysis plugin. Is there a way to add custom ACF fields to the analysis?

**Comment by jeroenrotty** [comment]
Hey @aronvandervalk,

Thank you for the issue. You might want to have a look at https://developer.yoast.com/customization/yoast-seo/adding-custom-data-analysis/ for customization like this.
