### ISSUE TITLE
Word Count not updating for ACF fields

### ISSUE THREAD

**Issue by detolah** [Yoast/yoast-acf-analysis#359]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.

The WordCount in the Insights tab does not update the words added using the ACF fields on a Post. However, the texts are detected, and an assessment report is provided in SEO and readability analysis.

### Please describe what you expected to happen and why.

The word count should update when content is added to the ACF field

### Technical info
* WordPress version: 6.3
* ACF Content Analysis for Yoast SEO version: 3.1
* Yoast SEO version: 21.5
* ACF type: pro
* ACF version: 6.2.2
* Relevant plugins in case of a bug:

**Comment by detolah** [comment]
Please inform the customer of conversation # 1063409 when this conversation has been closed.

**Comment by josevarghese** [comment]
Closing this, as we already have an issue opened at here: https://github.com/Yoast/wordpress-seo-premium/issues/3829
