### ISSUE TITLE
Critical vunerability, able to edit files to insert malware

### ISSUE THREAD

**Issue by jannickathdk** [Yoast/yoast-acf-analysis#382]
* [ ] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
You are able to edit site files using this link

https://siteurl.net/wp-content/plugins/acf-content-analysis-for-yoast-seo/vendor/composer/variables.php?dir=/home/siteurl/site/public_html&item=index.php&action=edit

which then allows malicious scripts to be added

### How can we reproduce this behavior?
1. 
2. 
3. 

### Technical info
* WordPress version:  6.6.2
* ACF Content Analysis for Yoast SEO version: 3.1
* Yoast SEO version: 23.6
* ACF type: pro 
* ACF version: 6.3.8 
* Relevant plugins in case of a bug:

**Comment by Djennez** [comment]
Removing due to security. Please see https://github.com/Yoast/yoast-acf-analysis/security/policy . We do take this report into consideration.
