### ISSUE TITLE
Plugin rewrite adding most fields and almost complete ACF v4/v5 support

### ISSUE THREAD

**Issue by kraftner** [Yoast/yoast-acf-analysis#4]
As already mentioned via mail I've done [an almost complete rewrite](https://github.com/kraftner/yoast-acf-analysis/tree/develop) that extends the support to most field types and also the Pro Version of ACF including fields like the repeater and flexible
fields.

Some comments about the implementation:
## Client Side / JS

I've split up the process in multiple steps.
1. Determine which ACF version is active
2. Collect all fields on the page. This differs depending on the ACF version. V4 (the public/free version) mostly does HTML scraping. For V5 there is a much nicer JS API to query fields.
3. The collected fields are passed to "scrapers" based on their field type that extract the actual data. This happens in bulk for each field type. This has the advantage that for fields that need to get data from the server (e.g. images) can do so in bulk instead of with multiple requests.
## Server Side / PHP

The general architecture is mostly the same. Only difference is that each field is parsed immediately as we do not have any performance advantage of bulk scraping as with client side JS.
## Config

There are [some things you can filter](https://github.com/kraftner/yoast-acf-analysis/blob/2e01c5189405e9a36e08e2176e6b0ee21052a39f/inc/class-yoast-acf-analysis.php#L61-L99):

Here is an example that defines `field_543e586f42311` as an headline.

```
add_filter( 'yoast_acf_config', function($config){
    $config['parser']['text']['headlines']['field_543e586f42311'] = 2;
    return $config;
} );
```

You can also completely [blacklist/ignore certain field types](https://github.com/kraftner/yoast-acf-analysis/blob/2e01c5189405e9a36e08e2176e6b0ee21052a39f/inc/class-yoast-acf-analysis.php#L65-L88)
### Final notes

I know this isn't polished yet and doesn't yet fully cover all field types and configurations. Some todos are listed in the source. Some others things (like config being one huge array) are debatable. So please see this as a draft. This is also the reason I didn't create a PR yet as I guess some changes will still be needed for merging.

Nevertheless as it mostly covers what I need for my use case I think now is a good time to go public and see where things go. I am looking forward to your feedback.

**Comment by kraftner** [comment]
Any news on this?

**Comment by omarreiss** [comment]
@kraftner thanks a lot for the tremendous amount of work! Sorry for not responding earlier. I am going to have someone take a look at your fork and gather some feedback. Let's see together how to proceed from there.

**Comment by kraftner** [comment]
Cool, looking forward to your feedback!

**Comment by kraftner** [comment]
As I'm seeing some activity here - I'll be at WCEU if someone wants to have a chat in person about this.

**Comment by omarreiss** [comment]
@kraftner Ah great, I am looking forward to it! Just followed you on Twitter. I am sure @moorscode would also like to meet.

**Comment by omarreiss** [comment]
Sorry for the delay on reviewing things. We've been a bit too busy lately...

**Comment by kraftner** [comment]
Don't worry, same issue here. :smile: 
I have my talk friday before lunch. After that I'll have my head free for other things like that. Just ping me. I'll also be at the contributor day, so we'll sure find some time and place to chat.

**Comment by omarreiss** [comment]
@kraftner great fun meeting you on WCEU. Can you submit a pull request on the `features/acf-5` branch so we can start working on getting this merged? Thanks!

**Comment by omarreiss** [comment]
And I gave you commit access 😸

**Comment by kraftner** [comment]
Thanks for the access and I also enjoyed meeting you at WCEU!
I'll be busy with my WCEU backlog this week, but I've scheduled some time for the second half of next week.

**Comment by kraftner** [comment]
As you might have noticed my estimation when I'll find time was too optimistic. I'll need to postpone this to beginning of August, sorry. Just wanted to let you know.

**Comment by omarreiss** [comment]
@kraftner maybe you could just find 5 minutes to PR your existing fork to the `features/acf-5` branch. I don't need you to do anything else at this point but it would be nice if we could start working on it a little bit. Thanks!

**Comment by kraftner** [comment]
Sorry, my comment above was the last thing I did before heading off for two well deserved weeks of offline-holidays :smile: 

This definitely needs some work now as Yoast as well as ACF have definitely changed some stuff since I wrote it. But this is a start.

**Comment by moorscode** [comment]
I have resolved the merge conflicts an merged the changes into our features branch.
We currently don't have a clear time slot in which we will be looking at/through all the changes but will update when the next planning cycle has been done.

Thanks!

**Comment by kraftner** [comment]
I just wanted to let you know that I have picked up development for this plugin again.

I haven't really added a lot functionality-wise, but ensured what is there works flawlessly with ACF 4 as well as ACF 5 Pro.

To do so I have spent quite some time writing some Unit Tests for the PHP, as well as System Tests using [NightwatchJS](http://nightwatchjs.org/) for the JS side of things. I've also worked in complying with the WP Coding Standards as well as prepared for using a Composer generated autoloader.

I'll push to `features/acf-5` in the next days and plan to spend the contributors day at WCEU to get this ready. I don't know who of you will be there, but maybe you've got time to chat with me so we can finally get this version out there.

**Comment by omarreiss** [comment]
@kraftner cool! We're going to be there with @moorscode and @atimmer. See you there!

**Comment by kraftner** [comment]
I've just pushed the current state of things to [`features/acf5`](https://github.com/Yoast/yoast-acf-analysis/tree/features/acf-5). It's not done yet, but almost. Just thought you might want to look at it (if you have time that this) before be might have a chat tomorrow.

**Comment by kraftner** [comment]
I've just pushed some more changes, basically removing all the code that was meant for the obsolete bulk analysis feature. I think the codebase is much more readable now (because smaller)

I'll try to prepare a basic VVV-based dev environment so you can easily try out the current state.

I hope that these are the final steps to get this out of the door soon. :smile:

**Comment by kraftner** [comment]
Okay I have just finished the [VVV-based dev environment](https://github.com/kraftner/yoast-acf-analysis-development). :tada: 

From my point of view the [`features/acf5`](https://github.com/Yoast/yoast-acf-analysis/tree/features/acf-5) branch is ready to get merged. But I'd appreciate if you could give it a test run to see if I've overlooked anything.

**Comment by kraftner** [comment]
As this is a very broad issue and has already lead to work on `features/acf5` that again is being worked on now via multiple other issues I am closing this.
