### ISSUE TITLE
Support localisation on GlotPress

### ISSUE THREAD

**Issue by GaryJones** [Yoast/yoast-acf-analysis#55]
https://translate.wordpress.org/locale/en-gb/default/wp-plugins/acf-content-analysis-for-yoast-seo is complaining that the plugin isn't properly prepared for localisation.

**Comment by kraftner** [comment]
@atimmer could this be related to #53 ?

**Comment by kraftner** [comment]
We forgot to rename the text domain before changing the plugin slug as part of the release. :cry: 

Working on a PR...

**Comment by GaryJones** [comment]
The problem seems to be, that the Text Domain header, and the `load_plugin_textdomain()` call both use `yoast-acf-analysis`, but the plugin slug (and what the main plugin file name should be as well), is `acf-content-analysis-for-yoast-seo`. They should all match the slug.

**Comment by atimmer** [comment]
Ah yes, I forgot about this part of the `Text Domain` on WordPress.org. @kraftner Would you be able to create a PR that changes the textdomain to `acf-content-analysis-for-yoast-seo`?

**Comment by kraftner** [comment]
On it.

Related #50

**Comment by kraftner** [comment]
As I am obviously not familiar with how .org handles translations - is the pot file in `languages` ignored anyway? If yes we should probably remove it, right?

**Comment by atimmer** [comment]
@kraftner Yes, the POT file is ignored. `load_plugin_textdomain` is also ignored. From WordPress 4.6 and onwards.

**Comment by kraftner** [comment]
I created a PR, but am unsure what to do about that POT file.
