### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by PhilipRowe** [Yoast/yoast-acf-analysis#57]
Hello

I am currently seeing error messages on my admin pages after installing the latest version of the module (2.0.0) the error message is "Warning: fopen(.......wordpress\wp-content\plugins\acf-content-analysis-for-yoast-seo): failed to open stream: Permission denied in"

https://github.com/Yoast/yoast-acf-analysis/blob/e3e72dd46d79e02b6c30c7801de62f7542132d2b/inc/class-yoast-acf-analysis-assets.php#L16

I can get the error message to go away by changing:
`$this->plugin_data = get_plugin_data( dirname( AC_SEO_ACF_ANALYSIS_PLUGIN_FILE ) );`
to:
`$this->plugin_data = get_plugin_data( AC_SEO_ACF_ANALYSIS_PLUGIN_FILE );`

With the `dirname()` the path its trying to load is:
`........wordpress\wp-content\plugins\acf-content-analysis-for-yoast-seo`
without the path is:
`........wordpress\wp-content\plugins\acf-content-analysis-for-yoast-seo\yoast-acf-analysis.php`

and it looks like `get_plugin_data()` wordpress function requires the Absolute path to the plugin file.

**Comment by kraftner** [comment]
Thanks for reporting and the analysis!

I think that sneaked in very last minute. Fortunately this is only a warning and doesn't do any serious harm. So you can can ignore it for now.

Nevertheless I have marked it as a bug and we will fix it ASAP.

**Comment by kraftner** [comment]
I have just created a PR that addresses this. If you want you can try the [`stories/fix-path-assets-class`](https://github.com/Yoast/yoast-acf-analysis/tree/stories/fix-path-assets-class) branch to see if that fixes it for you.
