### ISSUE TITLE
Does not recognize ACF when mu-plugin?

### ISSUE THREAD

**Issue by kyotoprotokollet** [Yoast/yoast-acf-analysis#6]
I get the error message "ACF Yoast Analysis requires Advanced Custom Fields (free or pro) to be installed and activated.". It is installed and activated (v 5.3.7), although as a mu-plugin.

**Comment by andrewdcato** [comment]
I'm not sure if this needs to be a separate issue or not, but I'm experiencing a similar problem. 

I usually bundle ACF in the theme and include it via my `funcitons.php` file, and this plugin can't detect ACF (latest versions of both the free and pro versions of the plugin exhibit the same behavior) when it's included that way.

**Comment by jrfnl** [comment]
@andrewdcato Similar issue and both are addressed in PR #8.

If would be helpful if you could check out the PR branch to test/confirm if that solves your problem. Feedback appreciated.
