### ISSUE TITLE
ACF Content Analysis for Yoast SEO version 2.0.0 throwing javascript error. "wpseoPostScrapperL10n is not defined". ACF fields like datepicker and related post dropdown dont work

### ISSUE THREAD

**Issue by ketanshah79** [Yoast/yoast-acf-analysis#61]
version: 2.0.0

There is an error in the javascript "wpseoPostScrapperL10n is not defined". (I think your javascript build process did not assemble the js file properly)

This broke few of the ACF fields like datepicker, related post dropdown etc.

I had to downgrade the version for things to work again.

Screenshot attached.

![screen shot 2017-08-24 at 14 34 14](https://user-images.githubusercontent.com/119186/29659113-d1eb00e6-88da-11e7-9cca-3bafe9ac9f19.jpg)

**Comment by ketanshah79** [comment]
@kraftner 

- yoast SEO premium version: 5.32
- ACF Pro : version 5.6.1
- It happens on add new post (post type) form page in WP Admin
- The ACF field for datepicker and related post are not usable at all as the datepicker popup UI and the related post autocomplete dropdown don't show up. This is because of the javascript error I pointed out earlier which probably affects the ACF javascript for those fields.

**Comment by moorscode** [comment]
We need to make sure that the scripts are loaded in the footer instead of the header to avoid a timing cause for this problem.

**Comment by bullpillaren** [comment]
Same issue [here](https://wordpress.org/support/topic/select-tool-for-acf-post-objects-not-working/)

**Comment by kraftner** [comment]
There is #67 ready to be tested that should fix this issue.

**Comment by kraftner** [comment]
fixed by #67
