### ISSUE TITLE
Breaks functionality of Search & Filter Pro plugin

### ISSUE THREAD

**Issue by erathje** [Yoast/yoast-acf-analysis#65]
With your plugin enabled, I cannot drag-and-drop fields in Search & Filter Pro, and actually just lost all my custom search/filter fields in there as a result... This may be due to the Javascript error mentioned by someone else. Not pleased!

**Comment by kraftner** [comment]
Can you check if you see any JavaScript Error when you open the Console (press F12)? Maybe something like `wpseoPostScraperL10n is not defined`?

**Comment by kraftner** [comment]
I am closing this as I am pretty sure it is a duplicate of #61. If you think this assumption is wrong feel free to comment so we can reopen the issue.
