### ISSUE TITLE
Thinks I'm running an old instal of Wordpress

### ISSUE THREAD

**Issue by Jimmydoodaa** [Yoast/yoast-acf-analysis#71]
"Yoast SEO: ACF Analysis requires Yoast SEO for WordPress 3.2 (or higher) to be installed and activated."

- I'm on Wordpress 4.8.1

**Comment by kraftner** [comment]
Version 3.2 refers to the version of "Yoast SEO for WordPress" and not WordPress itself. So you'll need to upgrade the Yoast Plugin to make it work.

Having said that I think the wording could be improved because right now I can see how one can read it the way you did.

**Comment by Jimmydoodaa** [comment]
Of course! That makes perfect sense when I read it back with my brain engaged. Thanks.
