### ISSUE TITLE
Parse error: syntax error, unexpected '[' in ......acf-content-analysis-for-yoast-seo/inc/configuration/class-yoast-acf-analysis-string-store.php on line 50

### ISSUE THREAD

**Issue by Jimmydoodaa** [Yoast/yoast-acf-analysis#72]
Crops up when activated alongside YOAST.

**Comment by kraftner** [comment]
Seems like you're running PHP<5.4. So we should be kind of supporting that so I'll mark this as a bug. Still I *highly* recommend you to upgrade PHP to a version of PHP that is still being maintained and getting security updates.

**Comment by devnihil** [comment]
Please inform the customer of conversation # 232850 when this conversation has been closed.
