### ISSUE TITLE
Renaming the main plugin file might have been a bad idea

### ISSUE THREAD

**Issue by kraftner** [Yoast/yoast-acf-analysis#75]
As reported [here](https://wordpress.org/support/topic/registered-plugin-file-change/) and [here](https://wordpress.org/support/topic/disabled-plugin-on-update-due-to-missing-plugin-file/) in the forum changing the main plugin file name might cause the plugin to be deactivated on update.

Not sure if it isn't too late to revert this though because then it would happen again for everyone that already has updated...

**Comment by bullpillaren** [comment]
According to WordPress.org 22% of the userbase has the latest version of the plugin.

**Comment by kraftner** [comment]
Okay so I guess that is an argument for changing this back as it will help more people on old versions than it might harm people already on 2.0. Right?

**Comment by bullpillaren** [comment]
Yeah, I think so. And the early adopters are probably more aware of things like this, especially since It has already happened once.

**Comment by kraftner** [comment]
Okay looking at this in more detail.

Before 2.0 the file was called
`yoast-seo-acf-content-analysis.php`.
Now it is called
`yoast-acf-analysis.php`.

So we could change it back to `yoast-seo-acf-content-analysis.php` but I am not sure if that is ideal either as this doesn't match the plugin slug. Anyone knows if that might cause further issues down the road? @GaryJones [hinted at something like this](https://github.com/Yoast/yoast-acf-analysis/issues/55#issuecomment-324029368).

**Comment by GaryJones** [comment]
While it's recommended to have the main plugin file name match the plugin slug, it's not critical. As you've seen, yes, changing the main plugin file name during an update will cause it to deactivate (WP doesn't re-scan updated plugin files to find the main plugin file again).

It's a slightly poor UX for it to become deactivated, but not the worse thing in the world, so if a change to the file name is needed again, I wouldn't worry too much about the impact. Better to fix sooner rather than later if that's the fix that's wanted.

**Comment by kraftner** [comment]
Okay so we have three options now:

1. `yoast-acf-analysis.php` - current name
2. `yoast-seo-acf-content-analysis.php` - name before 2.0
3. `acf-content-analysis-for-yoast-seo.php` - match the plugin slug

Personally I lean towards option 2. Opinions?

**Comment by bullpillaren** [comment]
Yeah, I made a mistake with the first release of the plugin (The plugin name could obviously not start with Yoast, so we changed it right before release and forgot to update the file name).

We'll have to live with my past mistakes, so option 2 is the way to go in my opinion.

**Comment by GaryJones** [comment]
Regardless of whatever the main plugin file name ends up as, I'd also recommend that the repo name (`yoast-acf-analysis`), and Composer package name (`yoast/yoast-acf-analysis`), at least ends up as either the old name or the new slug. The composer package could be marked as deprecated with a suggestion of the new package as it's replacement.

I don't see the benefit in having at least three variations of identifiers floating around.

(Aside: There are URLs in `composer.json` that incorrectly reference yet another variation of slug.)

**Comment by kraftner** [comment]
Yeah, right, there is still more mess here. Looks like we caused some mess while switching to publishing the rewrite via the old angry creative plugin...

Concerning the URLs in `composer.json` it seems like @GaryJones is talking about https://github.com/Yoast/yoast-acf-analysis/blob/38d79f93847210d4510a4e71014880e248fcc846/composer.json#L19 and https://github.com/Yoast/yoast-acf-analysis/blob/38d79f93847210d4510a4e71014880e248fcc846/composer.json#L41

The composer package isn't published on packagist so I think we can easily change the name there.

Renaming the repo might also make sense. It's just that we really need to make sure this time we clean up all references properly this time...

**Comment by kraftner** [comment]
One more thing: All the filters are currently prefixed with `yoast-acf-analysis` due to https://github.com/Yoast/yoast-acf-analysis/blob/38d79f93847210d4510a4e71014880e248fcc846/inc/class-yoast-acf-analysis-facade.php#L15
So we can't easily change that without another breaking change. :disappointed:

**Comment by kraftner** [comment]
I've started working on this in the [stories/unify-plugin-name](https://github.com/Yoast/yoast-acf-analysis/tree/stories/unify-plugin-name) branch but haven't done anything apart from fixing the .org links as the questions above haven't been decided yet.

**Comment by kraftner** [comment]
Okay so as time passed version distribution right now has changed to
- 46,3% for 2.0
- 53,6% for 1.2

So concerning the name of the main plugin file it really doesn't matter any more now as we'd deactivate the plugin on update for half of the users in any way.

That leaves us with the decision whether to rename this repo and the Composer package name. I'd say let's do it. Having all those different names is confusing even to me.

**Comment by omarreiss** [comment]
46% has a crappy experience for the second time (more annoying) vs 53% has a crappy experience for the first time. I think we can leave it as is, lessons learned ;-)

**Comment by kraftner** [comment]
This answers the first question.

We still need to decide if we rename the repo (and the Composer package name) as well as fix the wrong links as started in [stories/unify-plugin-name](https://github.com/Yoast/yoast-acf-analysis/tree/stories/unify-plugin-name).

**Comment by omarreiss** [comment]
The repo and the composer package name are now consistent with the plugin file right? Which I think is fine. The plugin name is the only inconsistent thing at the moment. However, I'd argue it is marketing territory. I say we leave it as it is. It expresses nicely what this plugin is about.

**Comment by kraftner** [comment]
Yes, although I think having a different slug on .org than repo/composer is still confusing. But let's leave it there for now. We can pick this up again in #87

**Comment by omarreiss** [comment]
Whoops, I overlooked that bit. Yeah, so let's change the package name and repo name to be compatible with the slug. So only the plugin file will remain what it is. @moorscode will send a support request to Github to unfork this repo.

**Comment by kraftner** [comment]
Okay than #92 needs to be updated afterwards to represent the new repo name.

**Comment by kraftner** [comment]
By renaming the repo we'll also need to update the following files in addition to `composer.json`.

- `README.md`
- `readme.txt`
- `package.json`

**Comment by moorscode** [comment]
This issue has been decided. Closing in favour of https://github.com/Yoast/yoast-acf-analysis/issues/99
