### ISSUE TITLE
Introduce Yoast Coding Standards

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#89]
To improve code quality and uniformity, we need to be able to check against the coding standards that we uphold.

Inspiration on how to implement can be found in any other Yoast plugin.

This needs to be run against the latest version of [Yoast CS](https://github.com/Yoast/yoastcs)

**Comment by kraftner** [comment]
Maybe that and running tests could also be automated with something like Travis.

**Comment by jrfnl** [comment]
Note: YoastCS will receive a big update in the very near future.

**Comment by kraftner** [comment]
Regarding Travis mentioned above see #101
