### ISSUE TITLE
SEO Analysis Tool Fails to scan the Custom Field WYSIWYG Editor

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoast-acf-analysis#9]
**What Was Expected:**
When a text, text-area, or WYSIWYG Editor was selected as a custom field, the Yoast SEO Analysis Tool would be able to scan and pick-up words in the custom field if Yoast ACF was activated

**What Happened Instead:**
The SEO Analysis Tool failed to pick-up the words.

Steps to Reproduce:
1.Create Post

2.Create Custom Field

![screen shot 2016-05-26 at 10 41 56 am](https://cloud.githubusercontent.com/assets/8238074/15578455/810567b0-232e-11e6-91f6-eb6e1c44fc0f.png)

3.Add custom field to the "Add custom fields to page analysis" in _SEO->Titles and Metas_ section

![screen shot 2016-06-08 at 9 49 53 am](https://cloud.githubusercontent.com/assets/8238074/15896453/6df25478-2d5e-11e6-9033-01bfd062e45e.png)

4.Add content to the post. Save. See that SEO Tool picks-up the words. Total Words: 69

![69 words](https://cloud.githubusercontent.com/assets/8238074/15578543/da57f27e-232e-11e6-9a69-ec117106dcdf.jpg)

5.Add words to Custom Field. See that SEO tool fails to pick-up words automatically. When post is updated the same result happens. Total Words still: 69

![still 69 words](https://cloud.githubusercontent.com/assets/8238074/15578626/308266e8-232f-11e6-9d46-63998f477dba.jpg)

**Tech Specs**
WordPress: 4.5.2 (on a multipress)
ACF: 4.4.7
Yoast SEO Premium: 3.5.2
Yoast ACF Analysis: 1.1.0
Theme: Twenty-Sixteen

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 120114 when this conversation has been closed.

**Comment by Pcosta88** [comment]
**In further testing it appears the plugin is able to recognize content in a text-field and text**
1.Create a text field
![4](https://cloud.githubusercontent.com/assets/8238074/18279591/15997812-7424-11e6-91e3-32fa52d11a6b.jpg)

2.Add content and see that plugin picks up Focus Keyword and word count
![2](https://cloud.githubusercontent.com/assets/8238074/18279597/1ae83358-7424-11e6-9d78-b7a7c878e798.jpg)

3.Create a text 

![text](https://cloud.githubusercontent.com/assets/8238074/18279681/65479902-7424-11e6-8981-b0c7f3ff82ab.jpg)

4.See the plugin pick up the text

![green](https://cloud.githubusercontent.com/assets/8238074/18279714/7e320d12-7424-11e6-83fa-36eac9513479.jpg)

**Retested: Tech Specs**
WordPress version: 4.6
Yoast SEO version: 2.4.2
ACF : 4.4.8
Yoast SEO: ACF Analysis: 1.2.0

Note: Does not work with WYSIYG editor

**Comment by kraftner** [comment]
Again, just like in #12 : WYSIYG is not yet implemented. See #2 for more information.

**Comment by Pcosta88** [comment]
@kraftner No problem! 👍  I wanted to update this issue report as it has a user as part of it.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 148057 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 153917 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Additionally, WYSIWYG content not appear in meta description preview.

![2](https://cloud.githubusercontent.com/assets/8238074/22432215/3310f826-e6e2-11e6-85ea-1551fd2a9afc.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 175993 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 207462 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 209513 when this conversation has been closed.

**Comment by kraftner** [comment]
This is now included in 2.0 which was released today! :tada:
