### ISSUE TITLE
Improve documentation (add filter examples)

### ISSUE THREAD

**Issue by kraftner** [Yoast/yoast-acf-analysis#95]
There are some filters in the plugin which are currently not documented anywhere.

**Comment by kraftner** [comment]
[These examples](https://angrycreative.se/en/open-source/acf-content-analysis-yoast-seo/#panel-8228-0-1-0 ) are wrong because the first three filters do not get an array but an instance of the [`Yoast_ACF_Analysis_String_Store`](https://github.com/Yoast/yoast-acf-analysis/blob/7e3df0c73f302393febe5bf88d31e14858239fbb/inc/configuration/class-yoast-acf-analysis-configuration.php#L9-L22) class.

**Comment by bullpillaren** [comment]
I've updated the [examples](https://angrycreative.se/en/open-source/acf-content-analysis-yoast-seo/#panel-8228-0-1-0). The first two now return an instance of the  `Yoast_ACF_Analysis_String_Store` class. As far as I can see the headlines filter should [return an array ](https://github.com/Yoast/yoast-acf-analysis/blob/develop/inc/class-ac-yoast-acf-content-analysis.php#L106).

**Comment by kraftner** [comment]
Thanks for having a look. All your examples completely **replace** the default settings and changes by e.g. other plugins instead of adding/removing things, which most of the time isn't a great idea. Especially with the `yoast-acf-analysis/blacklist_type` filter that [comes pre-filled with a lot of fields](https://github.com/Yoast/yoast-acf-analysis/blob/7e3df0c73f302393febe5bf88d31e14858239fbb/inc/class-ac-yoast-acf-content-analysis.php#L171-L218).

Those examples should better look like this:
```
add_filter( 'yoast-acf-analysis/blacklist_name', function ( $blacklist_name ) {
    $blacklist_name->add( 'my-field-name' );
    return $blacklist_name;
});
```
```
add_filter( 'yoast-acf-analysis/blacklist_type', function ( $blacklist_type ) {
    // text, image etc
    $blacklist_type->add( 'text' );
    $blacklist_type->add( 'image' );
    return $blacklist_type; 
});
```
```
add_filter( 'yoast-acf-analysis/headlines', function ( $headlines ) {
    // value from 1-6, 1=h1, 6=h6
    headlines['field_591eb45f2be86'] = 3
});
```

**Comment by bullpillaren** [comment]
Oh, of course, thanks for the heads up! I've updated the examples!

**Comment by kraftner** [comment]
I wonder if we should also put that into the `readme.txt`.

**Comment by kraftner** [comment]
@bullpillaren I just noticed an error in the headlines example, it lacks the `return` and a missing `$` so:

```
add_filter( 'yoast-acf-analysis/headlines', function ( $headlines ) {
    // value from 1-6, 1=h1, 6=h6
    $headlines['field_591eb45f2be86'] = 3
    return $headlines;
});
```

**Comment by bullpillaren** [comment]
Good catch, I've updated the example.
